name: ris_parser
description: Parser for RIS file format.
# version: 1.0.0
# homepage: https://github.com/fnx-io/ris_parser
# author: Dafe Simonek <dafesimonek@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
